<?php
/**
 * @file
 * Code for the Blog App feature.
 */

include_once('enterprise_blog.features.inc');

/**
 * Implements hook_form_FORM_ID_alter()
 */
function enterprise_blog_form_node_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#node']->type == 'enterprise_blog' && variable_get('admin_theme', '') == 'rubik') {
    drupal_add_js(drupal_get_path('module', 'enterprise_blog') . '/js/enterprise_blog.js');
  }
}

/**
 * Implements hook_node_view()
 */
function enterprise_blog_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'enterprise_blog' && in_array($view_mode, array('full', 'teaser'))) {
    drupal_add_css(drupal_get_path('module', 'enterprise_blog') . '/css/enterprise_blog.css');
  }
}

/**
 * Implements hook_views_data_alter()
 */
function enterprise_blog_views_data_alter(&$data) {
  // Add an additional option for published field
  $data['node']['status']['field']['output formats']['draft'] = array('', 'Draft');
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function enterprise_blog_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  global $user;

  // Add action link to 'node/add/blog' on 'blog' page.
  if ($root_path == 'blog') {
    $item = menu_get_item('node/add/enterprise-blog');
    if ($item['access'] && isset($router_item['page_arguments'][2]) && $router_item['page_arguments'][2] == $user->name) {
      $item['title'] = t('Post a new blog entry');
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
    elseif ($item['access']) {
      $item['title'] = t('Create new blog post');
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
    $item = menu_get_item('admin/content/blog');
    if ($item['access']) {
      $item['title'] = t('Administer Blogs');
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}

/**
 * Implements hook_permission()
 */
function enterprise_blog_permission() {
  return array(
    'administer blogs' => array(
      'title' => t('Administer Blog Posts'),
      'description' => t('Perform administration tasks for all blogs.'),
    ),
  );
}

/**
 * Implements hook_preprocess_comment()
 */
function enterprise_blog_preprocess_comment(&$variables) {
  $account = user_load($variables['user']->uid);
  // Add author picture
  if (isset($account->field_enterprise_blog_picture[(($account->language)?$account->language:'und')][0])) {
    $settings = array(
      'style_name' => 'enterprise_blog_thumbnail',
      'path' => $account->field_enterprise_blog_picture[(($account->language)?$account->language:'und')][0]['uri'],
      'attributes' => array(
        'alt' => $account->name,
        'title' => $account->name,
      ),
    );
    $variables['picture'] = theme('image_style', array($settings));
  }
}